RetroCollectNew/Controllers/GameListController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using ModelData;
using DataAccess.WorkUnits;
using ApplicationLayer.Business_Logic.Builders;
using Microsoft.AspNetCore.Hosting;
using Common.Enumerations;
using ApplicationLayer.Business_Logic.FileHandling;
using HttpAccess;
using ModelData.Request;
using ModelData.Responses;

namespace ApplicationLayer.Controllers
{    
    public class GameListController : Controller
    {
        private readonly IUnitOFWork _unitOFWork;     

        private readonly IGameListResponseBuilder _gameListResponseBuilder;

        private readonly IHostingEnvironment _hostingEnvironment;

        private readonly IFileHandler _fileHandler;

        private readonly IHttpManager _httpManager;

        public GameListController(IUnitOFWork unitOFWork, 
            IGameListResponseBuilder gameListResponseBuilder, 
            IHostingEnvironment hostingEnvironment,
            IFileHandler fileHandler,
            IHttpManager httpManager)            
        {
            _hostingEnvironment = hostingEnvironment;
            _unitOFWork = unitOFWork;        
            _gameListResponseBuilder = gameListResponseBuilder;
            _fileHandler = fileHandler;
            _httpManager = httpManager;
        }

        /// <summary>
        /// Sort and filted games from DB and return with view
        /// </summary>
        /// <param name="gameListRequestModel"></param>
        /// <returns></returns>
        #region Get Request
        [HttpGet]
        public IActionResult Index(GameListRequest gameListRequestModel)
        {
           // HttpManager goo = new HttpManager();
          //  goo.GetAll();

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            GameListResponse response = _gameListResponseBuilder.GetResponse(gameListRequestModel, User);

            return View (response);
        }


        /// <summary>
        /// Get game by ID and return with Details view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Details(string id)
        {
            if (id == null) return NotFound();
            var gameListModel = _httpManager.GetByID(id).Result;
            if (gameListModel == null) return NotFound();
            //gameListModel.ScreenShotURL = _fileHandler.LoadFiles(id.ToString());

            return View(gameListModel);
        }


        /// <summary>
        /// Return the create view
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }


        /// <summary>
        /// Return the edit view with along with retrieved record
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();
            var gameListModel = _unitOFWork.GameRepo.GetByID(id);

            gameListModel.ScreenShotURL = _fileHandler.LoadFiles(id.ToString());
            if (gameListModel == null) return NotFound();

            return View(gameListModel);
        }
        #endregion


        #region Post request
        /// <summary>
        /// Create new game in game list DB
        /// </summary>
        /// <param name="gameListModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind("Id,Cover,Developer,FirstReleaseDate,Publisher,ReleaseDateNA,ReleaseDateEU,ReleaseDateJP,Platform, ScreenShot")] GameListModel gameListModel)
        {
            if (ModelState.IsValid)
            {
                _unitOFWork.GameRepo.Insert(gameListModel);
                _unitOFWork.Commit();
                return RedirectToAction(nameof(Index));
            }
            return View(gameListModel);
        }


        /// <summary>
        /// Edit game in game list DB
        /// </summary>
        /// <param name="id"></param>
        /// <param name="gameListModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id, [Bind("Id,Cover,Developer,FirstReleaseDate,Publisher,ReleaseDateNA,ReleaseDateEU,ReleaseDateJP, Platform, ScreenShot")] GameListModel gameListModel)
        {
            //Save screenshots
            if (gameListModel.ScreenShot != null && gameListModel.ScreenShot.Count() > 0)
            { 
                _fileHandler.SaveFile(id.ToString(), gameListModel.ScreenShot);
            }

            if (id != gameListModel.Id) return NotFound();            

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOFWork.GameRepo.Update(gameListModel);
                    _unitOFWork.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameListModelExists(gameListModel.Id)) return NotFound();                    
                    else throw;                    
                }
            }
            return RedirectToAction(nameof(Edit) + "/" + id);
        }


        /// <summary>
        /// Delete game in game list DB
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _unitOFWork.GameRepo.Delete(id);
            _unitOFWork.Commit();
            
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Delete file
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]        
        [ValidateAntiForgeryToken]
        public IActionResult DeleteFile(string fileLocation, int id)
        {
            switch (_fileHandler.DeleteFile(fileLocation))
            {
                case FileResponse.FileNotFound:
                    return StatusCode(400, "Could not find file to delete");
                case FileResponse.Exception:
                    return StatusCode(500, "Could not delete file, please see logs for details.");            
            }
            return RedirectToAction(nameof(Edit) + "/" + id );
        }


        /// <summary>
        /// Ensure game list model exists
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool GameListModelExists(int id) =>  _unitOFWork.GameRepo.Get().Any(e => e.Id == id);
    }
    #endregion
}

RetroCollectNew/Views/GameList/Create.cshtml
@model ModelData.GameListModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>GameListModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateNA" class="control-label"></label>
                <input asp-for="ReleaseDateNA" class="form-control" />
                <span asp-validation-for="ReleaseDateNA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateEU" class="control-label"></label>
                <input asp-for="ReleaseDateEU" class="form-control" />
                <span asp-validation-for="ReleaseDateEU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateJP" class="control-label"></label>
                <input asp-for="ReleaseDateJP" class="form-control" />
                <span asp-validation-for="ReleaseDateJP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <input asp-for="Format" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScreenShot" class="control-label"></label>
                <input asp-for="ScreenShot" class="form-control" />
                <span asp-validation-for="ScreenShot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroCollectNew/Views/GameList/Delete.cshtml
@model ModelData.GameListModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GameListModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDateNA)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDateNA)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDateEU)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDateEU)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDateJP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDateJP)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Format)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RetroCollectNew/Views/GameList/Details.cshtml
@model ModelData.GameListModel
@using Common.Extensions;

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>GameListModel</h4>
    <hr />
    <div class="details-area">
        <div class="container">            
            <div class="row">
                <div class="col-xs-3" style="padding-left:10%%;">
                    <img src="@Model.Cover.Url.Replace("thumb", "cover_big")"/>
                </div>
                <div class="col-xs-9">                    
                    <div class="col-xs-12" style="font-size:50px">
                        @Html.DisplayFor(model => model.Name)   
                    </div>
                    
                    <div class="col-xs-12" style="font-size:24px; color:lightgray" >
                        <text>@Model.First_release_date.FromUnix()</text>
                    </div>
                    
                    <div class="col-xs-12">
                        @Html.DisplayFor(model => model.Popularity)
                    </div>
                    
                    <div class="col-xs-12">
                        @Html.DisplayFor(model => model.Rating)
                    </div>                    
                    <div class="form-group">
                        </br> </br>
                        <label for="exampleFormControlTextarea1">Summary</label>
                        <textarea style="background-color: transparent; color:white" class="form-control" id="exampleFormControlTextarea1" rows="3">@Html.DisplayFor(model => model.Summary)</textarea>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <br /><br />
</div>

<div class="container">
    <div class="row">
        <div id="myCarousel" class="carousel slide center" data-ride="carousel" >
            <!-- Indicators -->
            
    @if (Model.Screenshots != null)
    {
        <ol class="carousel-indicators">
            @for (int i = 0; i < Model.Screenshots.Count(); i++)
            {
                if (i == 0)
                {
                    <li data-target="#myCarousel" data-slide-to="@i" class="active"></li>
                }
                else
                {
                    <li data-target="#myCarousel" data-slide-to="@i"></li>
                }
            }

        </ol>
    
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                @if (Model.Screenshots != null)
            {
                    @foreach (var X in Model.Screenshots)
                {
                    if (Model.Screenshots.First() == X)
                    {
                            <div class="item active">
                                <a href='@X.Url.Replace("thumb", "screenshot_huge")'><img class="img-thumbnail center" src='@X.Url.Replace("thumb", "screenshot_big")' /></a>
                            </div>
                        }
                        else
                        {
                            <div class="item">
                                <a href='@X.Url.Replace("thumb", "screenshot_huge")'><img  class="img-thumbnail center" src='@X.Url.Replace("thumb", "screenshot_big")' /></a>
                            </div>

                        }
                    }
                }
            </div>
            
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
            }
        </div>
    </div>
 </div>

<div class="container">
    <div class="row">
        @if (Model.Videos != null)
        {
            @foreach (var y in Model.Videos)
            {
                <div class="col-xs-4">
                    <div class="video-section">

                        <iframe width="420" height="315"
                                src="https://www.youtube.com/embed/@y.Video_id"></iframe>
                    </div>
                </div>
            }
        }




    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;     
    }
    .details-area {
        color:white;
        font-family:roboto;
        }
    .video-section {
        border:thin;
        margin:5px;
    }
</style>

RetroCollectNew/Views/GameList/Edit.cshtml
@model ModelData.GameListModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>GameListModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateNA" class="control-label"></label>
                <input asp-for="ReleaseDateNA" class="form-control" />
                <span asp-validation-for="ReleaseDateNA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateEU" class="control-label"></label>
                <input asp-for="ReleaseDateEU" class="form-control" />
                <span asp-validation-for="ReleaseDateEU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDateJP" class="control-label"></label>
                <input asp-for="ReleaseDateJP" class="form-control" />
                <span asp-validation-for="ReleaseDateJP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <input asp-for="Format" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScreenShot" class="control-label"></label>
                <input asp-for="ScreenShot" class="form-control" multiple />
                <span asp-validation-for="ScreenShot" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
@using (Html.BeginForm("DeleteFile", "GameList", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            @if (Model.ScreenShotURL != null)
            { 
                @foreach (var X in Model.ScreenShotURL)
                {
                    <div class="col-xs-4">
                        <div class="thumbnail-section">
                            <button type="submit" class="close thumbnail-delete" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <a href="\@X.Replace("t_thumb", "screenshot_med")><img class="img-thumbnail" src="\@X" /></a>
                            @Html.Hidden("fileLocation", "\\" + @X)
                            @Html.Hidden("id", Model.Id)
                        </div>
                    </div>
                }
            }

        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}